run:
  timeout: 5m

output:
  format: tab
  sort-results: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dupl
    - errcheck
    - exhaustive
    - durationcheck
    - errorlint
    - exportloopref
    - forbidigo
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
