name: test

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Self test
        uses: ./
